name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      run: |
        echo ${{secrets.KEYSTORE}} | sed 's/./& /g'
        echo ${{secrets.SIGNING_KEY_ALIAS}} | sed 's/./& /g'
        echo ${{secrets.SIGNING_KEY_PASSWORD}} | sed 's/./& /g'
        echo ${{secrets.SIGNING_STORE_PASSWORD}} | sed 's/./& /g'
